# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rby1_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_dualarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_wholebody_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rby1_right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true

rby1_left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true

rby1_torso_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true

rby1_dualarm_controller:
  ros__parameters:
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true
    state_publish_rate: 100.0
    action_monitor_rate: 50.0
      
rby1_head_controller:
  ros__parameters:
    joints:
      - head_0
      - head_1
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true

rby1_wholebody_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - head_0
      - head_1
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints: true
    state_publish_rate: 100.0
    action_monitor_rate: 50.0

